const mongoose = require("mongoose");

main()
    .then(() => {
        console.log("Connection Successful");
    })
    .catch((err) => {
        console.log(err);
    });
async function main() {
    return await mongoose.connect("mongodb://127.0.0.1:27017/amazon");
}

const bookSchema = mongoose.Schema({
    title: {// this method is used when we have more than one constraint or constraint other than datatype.
        type: String, //we use type key to difine the datatype.
        required: true, // same as NOT NULL of SQL
        maxLength: 20
    },
    author: {
        type: String
    },
    price: {
        type: Number,
        min: [1, "price lower than required"] //we can set a custom error message for validation error by passing the value as array with first element as constraint and second element as custom error message.
    },
    discount: {
        type: Number,
        default: 0
    },
    category: {
        type: String,
        enum: ["fiction", "non-fiction"] //category's value can not be other than this.
    },
    genre: [String]
});

let Book = mongoose.model("Book", bookSchema);

let book1 = new Book({
    title: "The wizard of Oz",
    author: "Ksitiz",
    price: -1,
    category: "fiction",
    genre: ["Magic", "Fiction", "Famous"]
});

book1.save()
    .then(() => {
        console.log("Book1 saved");
    })
    .catch((err) => {
        // console.log("error is saving book1", err);
        console.log(err.errors.price.properties.message);//this will print the error message if it was generated by price.
    });